storagenetwork = false
tconstruct = false
sophisticatedbackpacks = true
fastfurnace = true
ironfurnaces = false
occultism = false
jei = true
ae2 = true
extendedcrafting = false
refinedstorageaddons = true
craftingcraft = false
toms_storage = false
sophisticatedcore = false
refinedstorage = true
prettypipes = false
fastbench = true
cyclic = false

